/*
 *  FUSION
 *  Copyright (c) 2012-2013 Alex Kosterin
 */

//
// Do not edit! This file was automatically generated by enumstrgen.py
//

#ifndef ENUMSTR_H
#define ENUMSTR_H

#include "include/nf.h"
#include "include/nf_internal.h"
#include "include/md.h"

namespace nf {
  const char* enumstr(op_t);
  const char* enumstr(_mtype_t);
  const char* enumstr(_md_sys_t);
  const char* enumstr(access_t);
  const char* enumstr(result_t);
  const char* enumstr(_oflags_t);
}

#endif //ENUMSTR_H

